### ISSUE TITLE
Issue compiling with cl.exe

### ISSUE THREAD

**Issue by jebej** [JuliaGeometry/Clipper.jl#21]
```
INFO: Building Clipper
INFO: Compiling with cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8036 : '/FoC:\Users\Jeremy\.julia\v0.5\Clipper\deps\..\src' not allowed with multiple source files
```

**Comment by jebej** [comment]
Removing the `/Fo$(path) ` option in the build script fixes the issue (and the tests pass), although it is necessary to have run
```
call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
```
before running julia to have all the environment variables properly set.

**Comment by maxvoxel8** [comment]
There is now an option to build with gcc on Windows. Is this acceptable or would you prefer continued cl support?

**Comment by jebej** [comment]
Did you actually try this option? I found that the tests did not pass, even though the DLL compiled fine...

**Comment by maxvoxel8** [comment]
They pass on my machine. I just made an update because someone was having trouble compiling with WinRPM. If this doesn't fix your problem please create an issue.

**Comment by jebej** [comment]
It fixed the problem, thanks! I have no preference regarding support of the VS compiler, it is really annoying to install do to the large size, and I assume not many people will have it installed. It might be simpler to just remove it.
