### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by ajkeller34** [JuliaGeometry/Clipper.jl#26]
It seems that when cl.exe is installed, builds can fail on Windows with the most recently tagged Clipper.jl. I don't have much information to give you because this was reported to me by someone else. After checking out master, the build succeeds using gcc provided by WinRPM (this is because the cl.exe part is commented out in build.jl now).

It'd be helpful if you could tag a new release whenever is convenient for you so that builds just work on Windows regardless of what is installed. Thanks!

**Comment by maxvoxel8** [comment]
Done.

**Comment by ajkeller34** [comment]
Thank you!
