### ISSUE TITLE
Should functions in Basic be closures?

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/Clipper.jl#5]
The Basic interface might preserve performance if we only need to instantiate one `Clip` and `Offset` object.

**Comment by jminardi** [comment]
Do you mean singletons?

**Comment by sjkelly** [comment]
I guess. I was thinking something like:

```
offset = offsetter() # closure so the Clipper.Offset object is not re instantiated with each call
offset(polys, dist)
```

If the first line is in global scope it is a singleton pattern through closures.

**Comment by jminardi** [comment]
Personally I'd avoid singletons unless there is strong evidence that we would get significant speedups.

**Comment by sjkelly** [comment]
I realized this could just be hidden in a call overload. Inside basic you define something like this:

```
const _ClipperOffset = 1

function _init()
_ClipperOffset = Clipper.Offset()
end

function offset()
    # incantation using the global Clipper object
end

```
